version: '3.7'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  rails:
    build: .
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    ports:
      - '3000:3000'
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db

volumes:
  postgres_data: {}
  app-storage: {}
